// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xvlfhvcdzevwfvqapnyl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2bGZodmNkemV2d2Z2cWFwbnlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNTI2OTMsImV4cCI6MjA1OTYyODY5M30.iFFIsmIIbu3MzuBovm4cQzvDCrl3P6abk5JFlIuJyQY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);